name: pension-planner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytest
  - python-dateutil
  - pandas
  - jupyter
  - ipyvuetify
  - ipywidgets
  - jupyterlab>=3.1
  - voila>=0.2.11
